# -*- coding: utf-8 -*-
"""Despliegue-Diabetes-Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcpfkq4ijXEjVDoDpY_9xExXBGvZ94a6
"""

import pickle
import pandas as pd
import streamlit as st

# Configuración inicial de la página
st.set_page_config(page_title="Predicción de Diabetes", layout="centered")
st.title('Sistema de Predicción de Diabetes')

@st.cache_resource
def cargar_modelo():
    filename = 'modelo-cla -diabetes.pkl'
    return pickle.load(open(filename, 'rb'))

modelo, encoder, variables, scaler = cargar_modelo()

# Diccionarios globales para el mapeo visual de las opciones
opciones_si_no = {0: "No", 1: "Sí"}
opciones_sexo = {0: "Femenino", 1: "Masculino"}
opciones_salud = {1: "Excelente", 2: "Muy Buena", 3: "Buena", 4: "Regular", 5: "Mala"}

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

st.subheader("Datos Clínicos y Demográficos")

# Variables numéricas
BMI = st.slider('Índice de Masa Corporal (BMI)', min_value=0.0, max_value=70.0, value=25.0, step=0.1)
MentHlth = st.slider('Días con mala salud mental (últimos 30 días)', 0, 30, 0)
PhysHlth = st.slider('Días con mala salud física (últimos 30 días)', 0, 30, 0)

# Variables categóricas y ordinales
GenHlth = st.selectbox('Salud General Autopercibida', [1, 2, 3, 4, 5], format_func=lambda x: opciones_salud.get(x))
Age = st.selectbox('Categoría de Edad (1: 18-24 ... 13: 80 o más)', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
Education = st.selectbox('Nivel Educativo alcanzado', [1, 2, 3, 4, 5, 6])
Income = st.selectbox('Nivel de Ingresos', [1, 2, 3, 4, 5, 6, 7, 8])

# Variables binarias optimizadas para el usuario
HighBP = st.selectbox('¿Tiene Presión Arterial Alta?', [0, 1], format_func=lambda x: opciones_si_no[x])
HighChol = st.selectbox('¿Tiene Colesterol Alto?', [0, 1], format_func=lambda x: opciones_si_no[x])
Smoker = st.selectbox('¿Ha fumado al menos 100 cigarrillos en su vida?', [0, 1], format_func=lambda x: opciones_si_no[x])
Stroke = st.selectbox('¿Ha sufrido un Accidente Cerebrovascular (Derrame)?', [0, 1], format_func=lambda x: opciones_si_no[x])
PhysActivity = st.selectbox('¿Realizó actividad física en los últimos 30 días?', [0, 1], format_func=lambda x: opciones_si_no[x])
Fruits = st.selectbox('¿Consume frutas diariamente?', [0, 1], format_func=lambda x: opciones_si_no[x])
Veggies = st.selectbox('¿Consume verduras diariamente?', [0, 1], format_func=lambda x: opciones_si_no[x])
Sex = st.selectbox('Sexo Biológico', [0, 1], format_func=lambda x: opciones_sexo[x])

# Crear diccionario con todas las variables en 0
data_dict = {col: 0 for col in variables}

# Variables numéricas
data_dict['BMI'] = BMI
data_dict['MentHlth'] = MentHlth
data_dict['PhysHlth'] = PhysHlth

# Variables categóricas
data_dict[f'GenHlth_{GenHlth}'] = 1
data_dict[f'Age_{Age}'] = 1
data_dict[f'Education_{Education}'] = 1
data_dict[f'Income_{Income}'] = 1

# Variables binarias (guardan internamente el 0 o 1 de la selección)
data_dict['HighBP_1'] = HighBP
data_dict['HighChol_1'] = HighChol
data_dict['Smoker_1'] = Smoker
data_dict['Stroke_1'] = Stroke
data_dict['PhysActivity_1'] = PhysActivity
data_dict['Fruits_1'] = Fruits
data_dict['Veggies_1'] = Veggies
data_dict['Sex_1'] = Sex

# Crear dataframe final
data = pd.DataFrame([data_dict])

st.markdown("---")

if st.button('Evaluar Paciente'):
    prediccion = modelo.predict(data)
    
    if prediccion[0] == 1:
        st.error('⚠️ El paciente puede tener diabetes')
    else:
        st.success('✅ El paciente no presenta indicadores de riesgo de diabetes')
        
    st.warning("Nota técnica: El modelo XGBoost tiene una precisión del 83.7%")
